### ISSUE TITLE
Arm bug.

### ISSUE THREAD

**Issue by InknightMC** [UltimateBoomer/Resolution-Control#44]
Has anyone else had their arm scaling with the resolution? Any ideas on how to fix?

![2023-06-24_08 39 43](https://github.com/UltimateBoomer/Resolution-Control/assets/137622894/057528f4-4641-4b29-be46-7e6a91f9ece5)

**Comment by emihead** [comment]
How did you fix it? I'm having this issue

**Comment by Lv44EnderShaman** [comment]
Recently this bug has reappeared for me as well. Would like to know if it's some kind of conflict with my graphics card settings; I'm using an AMD Ryzen 3550H APU, so the iGPU equivalent in it is a Radeon Vega 8 graphics chipset.

**Comment by Razatop** [comment]
Marked as completed with no solution is a crime.

**Comment by asdf-hash** [comment]
now it happens to the whole screen when i use sodium...
