### ISSUE TITLE
1.20.2?

### ISSUE THREAD

**Issue by motyI** [UltimateBoomer/Resolution-Control#48]
the 1.20.1 version of the mod doesn't seem to work on minecraft 1.20.2

the game launches normally, but when I open the resolution change screen and move my mouse, it crashes

**Comment by HowardZHY** [comment]
Yes Please Update it

**Comment by fl3tty** [comment]
bump

**Comment by JTModel3** [comment]
Yep

**Comment by nijahplays** [comment]
Yes please

**Comment by JTModel3** [comment]
Alright I think I got a working version for 1.20.2 let me know if anyone wants it.

**Comment by nijahplays** [comment]
> Alright I think I got a working version for 1.20.2 let me know if anyone wants it.

Will it be on modrinth?

**Comment by JTModel3** [comment]
> > Alright I think I got a working version for 1.20.2 let me know if anyone wants it.
> 
> Will it be on modrinth?

Probably not, most likely just github.

**Comment by 0AA55H** [comment]
@simplyknown if you have working version for 1.20.2 please send/share :)

**Comment by JTModel3** [comment]
@0AA55H @nijahplays [https://github.com/simplyknown/Resolution-Control/releases/tag/3.0.1](here)
(You have to copy and paste link into new tab)
Let me know if there are any issues as I did it fast. If the original creators don't update it before 1.20.3 I'll consider putting it on Modrinth.

**Comment by 0AA55H** [comment]
> @0AA55H @nijahplays [https://github.com/simplyknown/Resolution-Control/releases/tag/3.0.1](here) (You have to copy and paste link into new tab) Let me know if there are any issues as I did it fast. If the original creators don't update it before 1.20.3 I'll consider putting it on Modrinth.

@simplyknown it works great, thank you very much 😊

**Comment by fantahund** [comment]
[https://modrinth.com/mod/resolution-control-plus/version/1.20.2-3.0.0](url)

**Comment by fantahund** [comment]
[1.20.2 Modrinth](https://modrinth.com/mod/resolution-control-plus/version/1.20.2-3.0.0)
